# Étape 1 : Importation des bibliothèques et configuration

In [1]:
import os
import pandas as pd
import numpy as np
import spacy
from tqdm import tqdm
import subprocess
import sys

## Vérifions si spacy est installé et chargeons le modèle

In [2]:
try:
    nlp = spacy.load("en_core_web_sm")
except OSError:
    subprocess.run([sys.executable, "-m", "spacy", "download", "en_core_web_sm"])
    nlp = spacy.load("en_core_web_sm")

Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 12.1 MB/s eta 0:00:0000:0100:01
Installing collected packages: en-core-web-sm
Successfully installed en-core-web-sm-3.8.0
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')


### Accès aux données

In [3]:
RAW_PATH = "data/raw"
PROCESSED_PATH = "data/processed"

# Créons des dossiers s'ils n'existent pas encore
os.makedirs(RAW_PATH, exist_ok=True)
os.makedirs(PROCESSED_PATH, exist_ok=True)

# Étape 2 : Téléchargement des données

In [4]:
csv_files = [f for f in os.listdir(RAW_PATH) if f.endswith(".csv")]

for file_name in csv_files:
    file_path = os.path.join(RAW_PATH, file_name)
    print(f"\nTraitement du fichier : {file_name}")

     # Chargement du CSV
    df = pd.read_csv(file_path)
    print("Taille des données :", df.shape)
    display(df.head())

    print("Nombre de NaN par colonne :\n", df.isna().sum())
    print("Nombre de doublons : ", df.duplicated().sum())

    df = df.drop_duplicates()
    df = df.fillna("")

    # Enregistrement du CSV nettoyé
    clean_file_name = f"cleaned_{file_name}"
    clean_file_path = os.path.join(PROCESSED_PATH, clean_file_name)
    df.to_csv(clean_file_path, index=False)
    print(f"Les données nettoyées sont enregistrées dans {clean_file_path}")

Traitement du fichier : Fake.csv
Taille des données : (23481, 4)

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

Nombre de NaN par colonne :
 title      0
text       0
subject    0
date       0
dtype: int64
Nombre de doublons :  3
Les données nettoyées sont enregistrées dans data/processed/cleaned_Fake.csv

Traitement du fichier : True.csv
Taille des données : (21417, 4)

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

Nombre de NaN par colonne :
 title      0
text       0
subject    0
date       0
dtype: int64
Nombre de doublons :  206
Les données nettoyées sont enregistrées dans data/processed/cleaned_True.csv